version: "3"

networks:
  project_net:
    driver: bridge

services:
  nginx:
    container_name: project-nginx
    image: nginx:1.17
    networks:
      - project_net
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/run_nginx.sh:/opt/nginx/run_nginx.sh
    ports:
      - $WEB_PORT:80
    environment:
      - NGINX_PORT=80
      - APP_SERVICE=project-app
      - APP_PORT=5000
    command: /bin/bash -c /opt/nginx/run_nginx.sh
    depends_on:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  app:
    container_name: project-app
    image: project_app:0.2
    build:
      context: app/
      dockerfile: Dockerfile
    networks:
      - project_net
    ports:
      - $APP_PORT:5000
    environment:
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_SERVER=project-db
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - SECRET_KEY=$SECRET_KEY
    volumes:
      - ./db/:/opt/project/db/
    command: /bin/bash -c "/wait-for-it.sh db:3306 -t 0 && ./migrate.sh /opt/project/db/migrations/ && python app.py"
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  db:
    container_name: project-db
    image: mysql:5.7
    networks:
      - project_net
    ports:
      - $DB_PORT:3306
    environment:
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - ./db/lib/:/var/lib/mysql/
      - ./db/log/:/var/log/mysql/
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
