version: "3"

networks:
  mobilian_net:
    driver: bridge

services:
  nginx:
    container_name: mobilian-nginx
    image: nginx:1.17
    networks:
      - mobilian_net
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/run_nginx.sh:/opt/nginx/run_nginx.sh
    ports:
      - ${WEB_PORT}:80
    environment:
      - NGINX_PORT=80
      - APP_SERVICE=mobilian-app
      - APP_PORT=5000
    command: /bin/bash -c /opt/nginx/run_nginx.sh
    depends_on:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  app:
    container_name: mobilian-app
    image: mobilian_app:0.1
    build:
      context: app/
      dockerfile: Dockerfile
    networks:
      - mobilian_net
    ports:
      - ${APP_PORT}:5000
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./app/static/:/opt/mobilian/app/static/
      - ./mysql/:/opt/mobilian/db/
    command: /bin/bash -c "/wait-for-it.sh mysql:3306 -t 0 && ./migrate.sh /opt/mobilian/db/MIGRATED && python app.py"
    depends_on:
      - mysql
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  mysql:
    container_name: mobilian-db
    image: mysql:5.7
    networks:
      - mobilian_net
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./mysql/lib/:/var/lib/mysql/
      - ./mysql/log/:/var/log/mysql/
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
